apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: argocd
  namespace: istio-system
spec:
  members:
    # a list of projects joined into the service mesh
    - bookinfo
    - bookinfo2
    - bookinfo-3
    - bookinfo-3-mysql
