apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - shop
    - bookinfo-3
    - bookinfo-3-mysql
    - bookinfo-4
    - bookinfo-4-mysql
    - lets-chat
