kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/lniesz/lets-chat.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: lets-chat
  labels:
    app: lets-chat
    app.kubernetes.io/component: lets-chat
    app.kubernetes.io/instance: lets-chat
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: lets-chat-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'lets-chat:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/lniesz/lets-chat.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: lets-chat-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: lets-chat-git-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:b45daf0aa7b8c7f79f96ab43cdf6af38e395feec4fb0f7618dd904741b8cf074
    - type: ConfigChange
  runPolicy: Serial
