
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: lets-chat
spec:
  host: lets-chat
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: main
    labels:
      page: main
