kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/lniesz/lets-chat.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: lets-chat
  labels:
    app: lets-chat
    app.kubernetes.io/component: lets-chat
    app.kubernetes.io/instance: lets-chat
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: lets-chat-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  lookupPolicy:
    local: false
