kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-admin_password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: mongodb
  labels:
    template: mongodb-persistent-template
data:
  database-admin-password: cGFzc3dvcmQ=
  database-name: bGV0cy1jaGF0LWRi
  database-password: cGFzc3dvcmQ=
  database-user: ZGJ1c2Vy
type: Opaque
