
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lets-chat
spec:
  hosts:
  - {{ .Values.spec.url }}
  gateways:
  - lets-chat
  http: 
  - route:
    - destination:
        host: main
        port:
          number: 8080
