##################################################################################################
# Mysql db services
# credentials: root/password
##################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  rootpasswd: cGFzc3dvcmQ=
