apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pro-reverse-words
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pro-reverse-words
    server: {{ .Values.spec.destination.server }}
  project: reverse-words
  source:
    path: simple-app/reversewords_app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
